## List of configuration settings
## for vmagent-config-updater deployment
vmagentConfigUpdater:
  image:
    repository: dmitrykmoon/vmagent-config-updater
    pullPolicy: IfNotPresent
    tag: "heads-churn_rate_bench-0-g3bf9744"

  ## address with port for listening for HTTP requests
  listenAddr: ""

  ## How frequent to refresh the configuration.
  ## See also 'config.targetsToUpdatePercentage'
  configUpdateInterval: ""

  ## Percentage of the targets which would be updated
  ## with unique label on the next configuration update.
  ## Non-zero value will result in constant Churn Rate
  targetsToUpdatePercentage: "10"

  ## Defines how many scrape targets to generate in scrape config.
  ## Each target will have the same address defined by 'config.targetAddr'
  ## but each with unique label.
  targetsCount: "100"

  ## Address with port to use as target address in scrape config
  targetAddr: ""

  ## Defines how frequently to scrape targets
  scrapeInterval: ""

  ## Defines job name to scrape targets
  jobName: ""

  port: 8436


## List of configuration settings
## for vmagent deployment
vmagent:
  image:
    repository: victoriametrics/vmagent
    pullPolicy: IfNotPresent
    tag: "v1.72.0"
  ## defines which config to use
  ## if you want to use config from configmap.yml
  ## just change this param to
  ## /config/scrape.yml
  config: http://127.0.0.1:8436/api/v1/config

  ## Defines how frequently check config
  configCheckInterval: 10s

  ## targetsCount defines how many copies of nodeexporter
  ## to add as scrape targets.
  ## affects metrics volume and cardinality
  targetsCount: 1000

  ## defines how frequently scrape targets
  scrapeInterval: 5s

  ## remote-write configurations for vmagent
  ## vmagent will replicate data to all configured URLs
  remoteWrite:
      ## single-node: http://<victoriametrics-addr>:8428/api/v1/write
      ## cluster: http://<vminsert-addr>:8480/insert/0/prometheus/
    - url: ""
      ## auth token for VictoriaMetrics.
      ## leave empty if no token configured
      token: ""

  resources: { }
#    limits:
#      cpu: 2000m
#      memory: 2000Mi
#    requests:
#      cpu: 100m
#      memory: 100Mi

  nodeSelector: { }
  affinity: { }
  tolerations: [ ]

  port: 8429

## List of configuration settings
## for nginx + nodeexporter deployment
nodeExporter:
  image:
    repository: prom/node-exporter
    pullPolicy: IfNotPresent
    tag: "v1.3.1"

  ## Security context to be added to node-exporter pods
  ##
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534

  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi

  nodeSelector: { }
  affinity: { }
  tolerations: [ ]

  ## port for nodeexporter to run
  hostPort: 9101
  ## port for nginx to run
  ## vmagent will use this port for scraping
  hostPortCached: 9102

## List of configuration settings
## for vmalert deployment
vmalert:
  ## whether to deploy vmalert
  enabled: false
  image:
    repository: victoriametrics/vmalert
    pullPolicy: IfNotPresent
    tag: "latest"

  ## how often to evaluate rules
  evaluationInterval: 30s

  # creates vmalert deployment per url
  urls:
    ## datasource defines address for rule execution
    - datasource:
        ## single-node: http://<victoriametrics-addr>:8428
        ## cluster: http://<vminsert-addr>:8481/select/0/prometheus
        url: ""
        ## auth token for VictoriaMetrics.
        ## leave empty if no token configured
        token: ""
      remoteWrite:
        ## single-node: http://<victoriametrics-addr>:8428/
        ## cluster: http://<vminsert-addr>:8480/insert/0/prometheus/
        url: ""
        ## auth token for VictoriaMetrics.
        ## leave empty if no token configured
        token: ""

  resources: { }
    # limits:
    #   cpu: 200m
    #   memory: 50Mi
    # requests:
    #   cpu: 100m
    #   memory: 30Mi

  nodeSelector: {}
  affinity: { }
  tolerations: [ ]

  # vmalert port
  port: 8880
  # alertmanager port
  amPort: 9093
