apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "vm-benchmark.fullname" . }}-vmagent-cm
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "vm-benchmark.labels" . | nindent 4 }}
data:
  scrape.yml: |
    global:
      scrape_interval: {{ .Values.vmagent.scrapeInterval }}
    scrape_configs:
      - job_name: vmagent
        static_configs:
          - targets: ['localhost:8429']
      - job_name: node_exporter
        static_configs:
    {{- $svc :=  include "vm-benchmark.nginxCached" .  }}
    {{- $count := .Values.vmagent.targetsCount | int }}
    {{- range until $count }}
         - targets: ['{{ $svc }}']
           labels:
             host_number: cfg_{{.}}
    {{- end }}
