apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "vm-benchmark.fullname" . }}-vmagent-cm
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "vm-benchmark.labels" . | nindent 4 }}
data:
  scrape.yml: |
    global:
      scrape_interval: {{ .Values.vmagent.scrapeInterval }}
