apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vm-benchmark.fullname" . }}-vmagent
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "vm-benchmark.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
  {{- include "vm-benchmark.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/vmagent/configmap.yaml") . | sha256sum }}
      labels:
    {{- include "vm-benchmark.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: vmagent-config-updater
          image: "{{ .Values.vmagent_config_update.image.repository }}:{{ .Values.vmagent_config_update.image.tag }}"
          imagePullPolicy: "{{ .Values.vmagent_config_update.image.pullPolicy }}"

        - name: vmagent
          image: "{{ .Values.vmagent.image.repository }}:{{ .Values.vmagent.image.tag }}"
          imagePullPolicy: "{{ .Values.vmagent.image.pullPolicy }}"
          args:
            - --httpListenAddr=:{{ .Values.vmagent.port }}
            - --promscrape.config=http://localhost:8436/api/v1/config
            {{- range .Values.vmagent.remoteWrite }}
            - --remoteWrite.url={{ .url }}
            {{- if .token }}
            - --remoteWrite.bearerToken={{ .token }}
            {{- end }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.vmagent.port }}
          resources:
{{ toYaml .Values.vmagent.resources | indent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
      {{- if .Values.vmagent.tolerations }}
      tolerations:
{{ toYaml .Values.vmagent.tolerations | indent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: { { include "vm-benchmark.fullname" . } }-vmagent-cm
      {{- if .Values.vmagent.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.vmagent.nodeSelector | indent 8 }}
      {{- end }}
