{{ range $rsName, $rs := .Values.remoteStorages }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-benchmark.fullname" $ }}-vmagent-{{ $rsName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "prometheus-benchmark.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      job: vmagent
      remote-storage-name: {{ $rsName | quote }}
      {{- include "prometheus-benchmark.selectorLabels" $ | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        job: vmagent
        remote-storage-name: {{ $rsName | quote }}
        {{- include "prometheus-benchmark.labels" $ | nindent 8 }}
    spec:
      containers:
      - name: vmagent-config-updater
        image: "victoriametrics/vmagent-config-updater:v1.1.0"
        args:
        - --httpListenAddr=:8436
        - --targetsCount={{ $.Values.targetsCount }}
        - --targetAddr={{ printf "%s-nodeexporter.%s.svc:9102" (include "prometheus-benchmark.fullname" $) $.Release.Namespace }}
        - --scrapeInterval={{ $.Values.scrapeInterval }}
        - --scrapeConfigUpdatePercent={{ $.Values.scrapeConfigUpdatePercent }}
        - --scrapeConfigUpdateInterval={{ $.Values.scrapeConfigUpdateInterval }}
      - name: vmagent
        image: "victoriametrics/vmagent:{{ $.Values.vmtag }}"
        args:
        - --httpListenAddr=:8429
        - --remoteWrite.showURL=true
        - --promscrape.config=http://0.0.0.0:8436/api/v1/config
        - --promscrape.configCheckInterval=1s
        - --remoteWrite.url={{ $rs.writeURL }}
        - --remoteWrite.tmpDataPath=/vmagent-data
        - --remoteWrite.maxDiskUsagePerURL=2GiB
        - --remoteWrite.queues={{ $.Values.writeConcurrency }}
        {{- if $rs.writeBearerToken }}
        - --remoteWrite.bearerToken={{ $rs.writeBearerToken }}
        {{- end }}
        {{- if $rs.writeHeaders }}
        - --remoteWrite.headers={{ $rs.writeHeaders }}
        {{- end }}
        ports:
        - name: metrics
          containerPort: 8429
        volumeMounts:
        - mountPath: /vmagent-data
          name: vmagent-data
      volumes:
      - name: vmagent-data
        emptyDir: {}
---
{{ end }}
