{{ range $rsName, $rs := .Values.remoteStorages }}
{{ range $agentName, $config := $.Values.vmagents }}
{{- $agentConfig := deepCopy $.Values.vm | merge (deepCopy $.Values.vmagent) | merge $config }}
{{- $context := deepCopy $ | merge (dict "storage" $rsName "type" "agent" "component" $agentName) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-benchmark.fullname" $context }}-vmagent
  labels:
    {{- include "prometheus-benchmark.labels" $context | nindent 4 }}
spec:
  replicas: {{ $.Values.writeReplicas }}
  selector:
    matchLabels:
      {{- include "prometheus-benchmark.selectorLabels" $context | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/nginx-cm: {{ include (print $.Template.BasePath "/vmagent/nginx-cm.yaml") $ | sha256sum }}
      labels:
        {{- include "prometheus-benchmark.labels" $context | nindent 8 }}
    spec:
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: vmagent-config-updater
        image: victoriametrics/vmagent-config-updater:v1.1.0
        args:
        - --httpListenAddr=:8436
        - --targetsCount={{ $agentConfig.targetsCount }}
        - --targetAddr=0.0.0.0:9102
        - --scrapeInterval={{ $agentConfig.scrapeInterval }}
        - --scrapeConfigUpdatePercent={{ $agentConfig.scrapeConfigUpdatePercent }}
        - --scrapeConfigUpdateInterval={{ $agentConfig.scrapeConfigUpdateInterval }}
      - name: vmagent
        resources:
          requests:
            cpu: {{ $agentConfig.writeReplicaCPU }}
            memory: {{ $agentConfig.writeReplicaMem }}
          limits:
            memory: {{ $agentConfig.writeReplicaMem }}
        image: {{ $agentConfig.image.repository }}/vmagent:{{ $agentConfig.image.tag }}
        args:
        - --httpListenAddr=:8429
        - --remoteWrite.showURL
        - --promscrape.config=http://0.0.0.0:8436/api/v1/config
        - --promscrape.configCheckInterval={{ $agentConfig.scrapeConfigUpdateInterval }}
        {{- range $urlReplica := until ($rs.writeURLReplicas | default 1 | int) }}
        - --remoteWrite.url={{ $rs.writeURL }}?extra_label=url_replica={{ $urlReplica }}
        {{- end }}
        - --remoteWrite.tmpDataPath=/vmagent-data
        - --remoteWrite.maxDiskUsagePerURL=100MiB
        {{- if $agentConfig.writeConcurrency }}
        - --remoteWrite.queues={{ $agentConfig.writeConcurrency }}
        {{- end }}
        - --remoteWrite.label=component={{ $agentName }}
        - --promscrape.disableCompression
        - --promscrape.noStaleMarkers
        {{- if $rs.writeBearerToken }}
        - --remoteWrite.bearerToken={{ $rs.writeBearerToken }}
        {{- end }}
        {{- if $rs.writeHeaders }}
        - --remoteWrite.headers={{ $rs.writeHeaders }}
        {{- end }}
        {{- range $agentConfig.extraArgs }}
        - {{ . }}
        {{- end }}
        ports:
        - name: metrics
          containerPort: 8429
        volumeMounts:
        - mountPath: /vmagent-data
          name: vmagent-data
      - name: nodeexporter
        image: prom/node-exporter:v1.4.0
        args:
          - --path.procfs=/host/proc
          - --path.sysfs=/host/sys
          - --path.rootfs=/host/root
          # Note that disabled collectors are in sync with the alerting rules
          # When disabling a collector make sure to disable the related alerting rule
          - --no-collector.wifi
          - --no-collector.arp
          - --collector.processes
          - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+|run/containerd/.+|home/kubernetes/.+)($|/)
          - --web.max-requests=40
          - --web.listen-address=:9101
        volumeMounts:
          - name: proc
            mountPath: /host/proc
            readOnly: true
          - name: sys
            mountPath: /host/sys
            readOnly: true
          - name: root
            mountPath: /host/root
            mountPropagation: HostToContainer
            readOnly: true
        ports:
          - containerPort: 9101
            name: metrics
      - name: nginx
        image: nginx:1.23.1
        args:
          - nginx
          - -c
          - /opt/nginx/nginx.conf
        ports:
          - containerPort: 9102
            name: nginx
        volumeMounts:
          - mountPath: /opt/nginx
            name: nginx-cm
          - mountPath: /tmp/nginx
            name: nginx-cache
          - mountPath: /etc/nginx
            name: nginx-empty
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
      - name: vmagent-data
        emptyDir:
          medium: Memory
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: root
        hostPath:
          path: /
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-cm
        configMap:
          name: {{ include "prometheus-benchmark.fullname" $context }}-nginx-cm
      - name: nginx-empty
        emptyDir: {}
{{ end }}
{{ end }}
