{{ range $rsName, $config := .Values.remoteStorages }}
{{- if eq $config.type "vmsingle" }}
{{- $rsConfig := deepCopy $.Values.vm | merge (deepCopy $.Values.vmsingle) | merge $config }}
{{- $context := deepCopy $ | merge (dict "storage" $rsName "type" "storage" "component" $rsName) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "prometheus-benchmark.fullname" $context }}-vmsingle-cm
  labels:
    {{- include "prometheus-benchmark.labels" $context | nindent 4 }}
data:
  scrape.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
    - job_name: pods
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          own_namespace: true
        selectors:
        - role: pod
          label: 'chart-name={{ include "prometheus-benchmark.fullname" $context }}'
      relabel_configs:
      - if: '{__meta_kubernetes_pod_container_port_name="metrics"}'
        action: keep
      - action: labelmap
        regex: "__meta_kubernetes_pod_label_(.+)"
      - action: labeldrop
        regex: "pod_template_hash"
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container
{{- end }}
{{- end }}
