{{- if .Values.vmalert.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "vm-benchmark.fullname" . }}-alertmanager-cm
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "vm-benchmark.labels" . | nindent 4 }}
data:
  alertmanager.yml: |
    route:
      receiver: blackhole
    receivers:
      - name: blackhole
{{- end }}