{{- if .Values.vmalert.enabled -}}
{{ range $idx, $url := .Values.vmalert.urls }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vm-benchmark.fullname" $ }}-vmalert-{{ $idx}}
  namespace: {{ $.Release.Namespace }}
  labels:
  {{- include "vm-benchmark.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
  {{- include "vm-benchmark.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/vmalert/vmalert-cm.yaml") $ | sha256sum }}
      labels:
   {{- include "vm-benchmark.selectorLabels" $ | nindent 8 }}
    spec:
      containers:
        - name: vmalert
          image: "{{ $.Values.vmalert.image.repository }}:{{ $.Values.vmalert.image.tag }}"
          imagePullPolicy: "{{ $.Values.vmalert.image.pullPolicy }}"
          args:
            - --httpListenAddr=:{{ $.Values.vmalert.port }}
            - --notifier.url=http://127.0.0.1:{{ $.Values.vmalert.amPort }}
            - --rule=/config/alerts.yml
            - --evaluationInterval={{ $.Values.vmalert.evaluationInterval }}
            - --datasource.url={{ $url.datasource.url }}
            {{- if $url.datasource.token }}
            - --datasource.bearerToken={{ $url.datasource.token }}
            {{- end }}
            {{- if $url.remoteWrite.url }}
            - --remoteWrite.url={{ $url.remoteWrite.url }}
            {{- end }}
            {{- if $url.remoteWrite.token }}
            - --remoteWrite.bearerToken={{ $url.remoteWrite.token }}
          {{- end }}
          ports:
            - name: metrics
              containerPort: {{ $.Values.vmalert.port }}
          resources:
{{ toYaml $.Values.vmalert.resources | indent 12 }}
          volumeMounts:
            - name: vmalert-cfg
              mountPath: /config

        - name: alertmanager
          image: prom/alertmanager
          imagePullPolicy: "{{ $.Values.vmalert.image.pullPolicy }}"
          args:
            - --web.listen-address=:{{ $.Values.vmalert.amPort }}
            - --config.file=/config/alertmanager.yml
          ports:
            - name: am
              containerPort: {{ $.Values.vmalert.amPort }}
          resources:
          {{ toYaml $.Values.vmalert.resources | indent 12 }}
          volumeMounts:
            - name: alertmanager-cfg
              mountPath: /config
      {{- if $.Values.vmalert.tolerations }}
      tolerations:
{{ toYaml $.Values.vmalert.tolerations | indent 8 }}
      {{- end }}
      {{- if $.Values.vmalert.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.vmalert.nodeSelector | indent 8 }}
      {{- end }}
      volumes:
        - name: vmalert-cfg
          configMap:
            name: {{ include "vm-benchmark.fullname" $ }}-vmalert-cm
        - name: alertmanager-cfg
          configMap:
            name: {{ include "vm-benchmark.fullname" $ }}-alertmanager-cm
---
{{ end }}
{{- end }}